"""First revision

Revision ID: 59c215b97a76
Revises: 
Create Date: 2024-09-11 18:35:54.583779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c215b97a76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue', sa.String(length=255), nullable=False),
    sa.Column('requested', sa.DateTime(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue', 'requested')
    )
    op.create_index(op.f('ix_requests_issue'), 'requests', ['issue'], unique=False)
    op.create_index(op.f('ix_requests_requested'), 'requests', ['requested'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_requested'), table_name='requests')
    op.drop_index(op.f('ix_requests_issue'), table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###
