"""added created and created_by to issuedata

Revision ID: 898cce3383d8
Revises: c654b7a7c4f5
Create Date: 2025-01-19 16:58:39.207021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898cce3383d8'
down_revision: Union[str, None] = 'c654b7a7c4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_data', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('issue_data', sa.Column('created_by', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_data', 'created_by')
    op.drop_column('issue_data', 'created')
    # ### end Alembic commands ###
