"""issue_data added

Revision ID: aadb0d8e76f4
Revises: 59c215b97a76
Create Date: 2024-09-11 21:25:22.692901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aadb0d8e76f4'
down_revision: Union[str, None] = '59c215b97a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue', sa.String(length=255), nullable=False),
    sa.Column('computed', sa.DateTime(), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue', 'computed')
    )
    op.create_index(op.f('ix_issue_data_computed'), 'issue_data', ['computed'], unique=False)
    op.create_index(op.f('ix_issue_data_issue'), 'issue_data', ['issue'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_data_issue'), table_name='issue_data')
    op.drop_index(op.f('ix_issue_data_computed'), table_name='issue_data')
    op.drop_table('issue_data')
    # ### end Alembic commands ###
