"""issue_id_project_id_summary

Revision ID: c654b7a7c4f5
Revises: aadb0d8e76f4
Create Date: 2024-10-21 22:44:19.652036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c654b7a7c4f5'
down_revision: Union[str, None] = 'aadb0d8e76f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_data', sa.Column('issue_id', sa.Integer(), nullable=True))
    op.add_column('issue_data', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('issue_data', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_data', 'summary')
    op.drop_column('issue_data', 'project_id')
    op.drop_column('issue_data', 'issue_id')
    # ### end Alembic commands ###
